# 입문자를 위한, 파이썬/R 데이터 분석

]

## Today's mission

- FDR(FinanceDataReader)를 통한 상장종목 수집
- 한국거래소(KRX) 전체 종목 분석
- FDR를 통한 개별 종목 데이터 수집 및 분석 / 과학적 기수법

]

## FDR(FinanceDataReader)를 통한 상장종목 수집

### FinanceDataReader 란?

* 한국 주식 가격, 미국주식 가격, 지수, 환율, 암호화폐 가격, 종목 리스팅 등 금융 데이터 수집 라이브러리

* [FinanceData/FinanceDataReader: Financial data reader](https://github.com/FinanceData/FinanceDataReader)
* [FinanceDataReader 사용자 안내서 | FinanceData](https://financedata.github.io/posts/finance-data-reader-users-guide.html)
* https://pandas-datareader.readthedocs.io/en/latest/readers/index.html

## 설치

In [1]:
# 주석을 풀고 설치해 주세요. 주석을 푸는 방법은 아래 코드의 맨 앞에 있는 #을 지워주시면 됩니다.
# !pip install -U finance-datareader

In [2]:
# !pip install plotly

## 라이브러리 불러오기

In [3]:
# 데이터 분석을 위해 pandas 불러오기
import pandas as pd

In [4]:
# FinanceDataReader 를 fdr 별칭으로 불러옵니다.
# 라이브러리의 version을 확인하고 싶을 때는 .__version__ 으로 확인합니다. 
import FinanceDataReader as fdr
fdr.__version__

'0.9.93'

## 한국거래소 상장종목 전체 가져오기

참고 : http://data.krx.co.kr/contents/MDC/MDI/mdiLoader/index.cmd?menuId=MDC0201020101 > [종목정보] > [전종목 기본종목]

In [5]:
# 도움말을 보고자 할때는 ? 를 사용하고 소스코드를 볼 때는 ??를 사용합니다.
# 주피터 노트북에서는 함수나 메소드의 괄호 안에서 shift + tab 키를 누르면 도움말을 볼 수 있습니다.
fdr.StockListing?

Signature: fdr.StockListing(market: str, start=None, end=None) -> pandas.core.frame.DataFrame
Docstring:
read stock list of stock exchanges
* market: 'KRX', 'KOSPI', 'KOSDAQ', 'KONEX', 'KRX-MARCAP',
        'KRX-DESC', 'KOSPI-DESC', 'KOSDAQ-DESC', 'KONEX-DESC',
        'KRX-DELISTING', 'KRX-ADMINISTRATIVE', 'KRX-MARCAP',
        'NASDAQ', 'NYSE', 'AMEX', 'SSE', 'SZSE', 'HKEX', 'TSE', 'HOSE',
        'S&P500',
        'ETF/KR',
File:      ~/opt/anaconda3/envs/dl/lib/python3.9/site-packages/FinanceDataReader/data.py
Type:      function

In [6]:
# KRX : KRX 종목 전체
# KOSPI : KOSPI 종목
# KOSDAQ : KOSDAQ 종목
# KONEX : KONEX 종목
# NASDAQ : 나스닥 종목
# NYSE : 뉴욕증권거래소 종목
# SP500 : S&P500 종목
df_krx = fdr.StockListing("KRX")
df_krx

,Code,ISU_CD,Name,Market,Dept,Close,ChangeCode,Changes,ChagesRatio,Open,High,Low,Volume,Amount,Marcap,Stocks,MarketId
0,005930,KR7005930003,삼성전자,KOSPI,,79400,1,1100,1.40,79500,79800,78700,4797281,380063908100,474000734470000,5969782550,STK
1,000660,KR7000660001,SK하이닉스,KOSPI,,199800,1,5900,3.04,198700,200500,198100,1422029,283249610300,145454872527000,728002365,STK
2,373220,KR7373220003,LG에너지솔루션,KOSPI,,330000,1,500,0.15,333000,334000,327000,40538,13385655000,77220000000000,234000000,STK
3,207940,KR7207940008,삼성바이오로직스,KOSPI,,916000,2,-14000,-1.51,931000,934000,915000,32421,29916114000,65195384000000,71174000,STK
4,005380,KR7005380001,현대차,KOSPI,,258000,1,3000,1.18,258000,261000,255000,328362,84671381000,54029377278000,209416191,STK
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2823,413300,KR7413300005,티엘엔지니어링,KONEX,일반기업부,1900,1,201,11.83,1900,1900,1900,1,1900,2480478500,1305515,KNX
2824,245450,KR7245450002,씨앤에스링크,KONEX,일반기업부,1398,1,123,9.65,1398,1398,1398,11,15378,2208784080,1579960,KNX
2825,288490,KR7288490006,나라소프트,KONEX,일반기업부,120,1,7,6.19,125,125,120,199,24380,2096589240,17471577,KNX
2826,236030,KR7236030003,씨알푸드,KONEX,일반기업부,555,1,28,5.31,570,580,450,64571,29743280,1128499260,2033332,KNX
2827,308700,KR7308700004,테크엔,KONEX,일반기업부,199,0,0,0.00,0,0,0,0,0,796000000,4000000,KNX

In [7]:
fdr.StockListing("NASDAQ")

100%|██████████| 3709/3709 [00:03<00:00, 1076.58it/s]

,Symbol,Name,IndustryCode,Industry
0,AAPL,Apple Inc,57106020,전화 및 소형 장치
1,NVDA,NVIDIA Corp,57101010,반도체
2,MSFT,Microsoft Corp,57201020,소프트웨어
3,AMZN,Amazon.com Inc,53402010,백화점
4,META,Meta Platforms Inc,57201030,온라인 서비스
...,...,...,...,...
3704,NYMTI,New York Mortgage Trust Inc 9 125 Senior Notes...,60102040,특수 REITs
3705,RFAIR,RF Acquisition II Right 01st May 2026,55601010,투자 지주 회사
3706,FSHPR,Flag Ship Acquisition Rights,55601010,투자 지주 회사
3707,VLYPN,Valley National Bancorp 8 250 Fixed Rate Reset...,55101010,은행
3708,YHNAU,YHN Acquisition I Units,55601010,투자 지주 회사

In [8]:
# 한국거래소 상장종목 전체 가져오기
df_krx.head()

,Code,ISU_CD,Name,Market,Dept,Close,ChangeCode,Changes,ChagesRatio,Open,High,Low,Volume,Amount,Marcap,Stocks,MarketId
0,005930,KR7005930003,삼성전자,KOSPI,,79400,1,1100,1.40,79500,79800,78700,4797281,380063908100,474000734470000,5969782550,STK
1,000660,KR7000660001,SK하이닉스,KOSPI,,199800,1,5900,3.04,198700,200500,198100,1422029,283249610300,145454872527000,728002365,STK
2,373220,KR7373220003,LG에너지솔루션,KOSPI,,330000,1,500,0.15,333000,334000,327000,40538,13385655000,77220000000000,234000000,STK
3,207940,KR7207940008,삼성바이오로직스,KOSPI,,916000,2,-14000,-1.51,931000,934000,915000,32421,29916114000,65195384000000,71174000,STK
4,005380,KR7005380001,현대차,KOSPI,,258000,1,3000,1.18,258000,261000,255000,328362,84671381000,54029377278000,209416191,STK

In [9]:
df_krx[df_krx['Market']=='KOSDAQ']

,Code,ISU_CD,Name,Market,Dept,Close,ChangeCode,Changes,ChagesRatio,Open,High,Low,Volume,Amount,Marcap,Stocks,MarketId
37,028300,KR7028300002,HLB,KOSDAQ,중견기업부,90600,1,100,0.11,90500,91700,89700,302531,27432589400,11854589978400,130845364,KSQ
39,086520,KR7086520004,에코프로,KOSDAQ,우량기업부,85500,3,0,0.00,86600,87000,85100,295339,25377853500,11383328070000,133138340,KSQ
90,348370,KR7348370008,엔켐,KOSDAQ,벤처기업부,202000,2,-3000,-1.46,212500,214500,199800,141285,29076383000,4198958446000,20786923,KSQ
106,000250,KR7000250001,삼천당제약,KOSDAQ,중견기업부,152100,2,-3000,-1.93,157400,158300,151900,186485,28964667200,3567881491200,23457472,KSQ
122,068760,KR7068760008,셀트리온제약,KOSDAQ,우량기업부,70800,2,-1400,-1.94,72400,73400,70600,143960,10335499700,2945043032400,41596653,KSQ
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2775,475240,KR7475240008,하나32호스팩,KOSDAQ,SPAC(소속부없음),2190,3,0,0.00,2190,2200,2190,1036,2268950,7008000000,3200000,KSQ
2777,323230,KR7323230003,엠에프엠코리아,KOSDAQ,관리종목(소속부없음),161,0,0,0.00,0,0,0,0,0,6967193212,43274492,KSQ
2778,438580,KR7438580003,엔에이치스팩25호,KOSDAQ,SPAC(소속부없음),2295,1,15,0.66,2275,2300,2250,2391,5381845,6930900000,3020000,KSQ
2814,021045,KR7021041009,대호특수강우,KOSDAQ,중견기업부,7600,3,0,0.00,7600,7600,7600,11,83600,3224269600,424246,KSQ
2821,032685,KR7032681009,소프트센우,KOSDAQ,중견기업부,7960,2,-40,-0.50,7850,8000,7850,17,133710,2842850320,357142,KSQ

In [10]:
# 행과 열의 크기를 봅니다.(행, 열) 순
df_krx.shape

(2828, 17)

In [11]:
# 전체 데이터프레임의 요약정보를 봅니다.
df_krx.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2828 entries, 0 to 2827
Data columns (total 17 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Code         2828 non-null   object
 1   ISU_CD       2828 non-null   object
 2   Name         2828 non-null   object
 3   Market       2828 non-null   object
 4   Dept         2828 non-null   object
 5   Close        2828 non-null   object
 6   ChangeCode   2828 non-null   object
 7   Changes      2828 non-null   int64
 8   ChagesRatio  2828 non-null   float64
 9   Open         2828 non-null   int64
 10  High         2828 non-null   int64
 11  Low          2828 non-null   int64
 12  Volume       2828 non-null   int64
 13  Amount       2828 non-null   int64
 14  Marcap       2828 non-null   int64
 15  Stocks       2828 non-null   int64
 16  MarketId     2828 non-null   object
dtypes: float64(1), int64(8), object(8)
memory usage: 375.7+ KB

In [12]:
# 기술통계 값을 요약합니다.
df_krx.describe()

,Changes,ChagesRatio,Open,High,Low,Volume,Amount,Marcap,Stocks
count,2828.000000,2828.000000,2828.000000,2828.000000,2828.000000,2.828000e+03,2.828000e+03,2.828000e+03,2.828000e+03
mean,82.800566,0.746344,18818.427511,19076.301627,18571.738331,2.302140e+05,2.488983e+09,9.170845e+11,4.220746e+07
std,855.586646,2.784334,48164.691570,48537.738342,47470.925930,1.427480e+06,1.330002e+10,9.900145e+12,1.332833e+08
min,-14000.000000,-25.360000,0.000000,0.000000,0.000000,0.000000e+00,0.000000e+00,7.960000e+08,2.000000e+05
25%,-5.000000,-0.180000,2183.750000,2203.750000,2165.000000,3.470250e+03,1.695992e+07,4.977051e+10,1.025244e+07
50%,11.000000,0.360000,5430.000000,5560.000000,5360.000000,1.780250e+04,9.257996e+07,1.052303e+11,1.991211e+07
75%,95.000000,1.432500,14425.000000,14667.500000,14155.000000,7.483625e+04,5.788642e+08,2.630168e+11,4.203607e+07
max,14500.000000,29.970000,931000.000000,934000.000000,915000.000000,5.072665e+07,3.800639e+11,4.740007e+14,5.969783e+09

In [13]:
pd.set_option('display.max_row', 60)
df_krx

,Code,ISU_CD,Name,Market,Dept,Close,ChangeCode,Changes,ChagesRatio,Open,High,Low,Volume,Amount,Marcap,Stocks,MarketId
0,005930,KR7005930003,삼성전자,KOSPI,,79400,1,1100,1.40,79500,79800,78700,4797281,380063908100,474000734470000,5969782550,STK
1,000660,KR7000660001,SK하이닉스,KOSPI,,199800,1,5900,3.04,198700,200500,198100,1422029,283249610300,145454872527000,728002365,STK
2,373220,KR7373220003,LG에너지솔루션,KOSPI,,330000,1,500,0.15,333000,334000,327000,40538,13385655000,77220000000000,234000000,STK
3,207940,KR7207940008,삼성바이오로직스,KOSPI,,916000,2,-14000,-1.51,931000,934000,915000,32421,29916114000,65195384000000,71174000,STK
4,005380,KR7005380001,현대차,KOSPI,,258000,1,3000,1.18,258000,261000,255000,328362,84671381000,54029377278000,209416191,STK
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2823,413300,KR7413300005,티엘엔지니어링,KONEX,일반기업부,1900,1,201,11.83,1900,1900,1900,1,1900,2480478500,1305515,KNX
2824,245450,KR7245450002,씨앤에스링크,KONEX,일반기업부,1398,1,123,9.65,1398,1398,1398,11,15378,2208784080,1579960,KNX
2825,288490,KR7288490006,나라소프트,KONEX,일반기업부,120,1,7,6.19,125,125,120,199,24380,2096589240,17471577,KNX
2826,236030,KR7236030003,씨알푸드,KONEX,일반기업부,555,1,28,5.31,570,580,450,64571,29743280,1128499260,2033332,KNX
2827,308700,KR7308700004,테크엔,KONEX,일반기업부,199,0,0,0.00,0,0,0,0,0,796000000,4000000,KNX

## 파일로 저장하고 불러오기
<img src="https://pandas.pydata.org/docs/_images/02_io_readwrite.svg">

In [14]:
# head 로 미리보기
df_krx.head()

,Code,ISU_CD,Name,Market,Dept,Close,ChangeCode,Changes,ChagesRatio,Open,High,Low,Volume,Amount,Marcap,Stocks,MarketId
0,005930,KR7005930003,삼성전자,KOSPI,,79400,1,1100,1.40,79500,79800,78700,4797281,380063908100,474000734470000,5969782550,STK
1,000660,KR7000660001,SK하이닉스,KOSPI,,199800,1,5900,3.04,198700,200500,198100,1422029,283249610300,145454872527000,728002365,STK
2,373220,KR7373220003,LG에너지솔루션,KOSPI,,330000,1,500,0.15,333000,334000,327000,40538,13385655000,77220000000000,234000000,STK
3,207940,KR7207940008,삼성바이오로직스,KOSPI,,916000,2,-14000,-1.51,931000,934000,915000,32421,29916114000,65195384000000,71174000,STK
4,005380,KR7005380001,현대차,KOSPI,,258000,1,3000,1.18,258000,261000,255000,328362,84671381000,54029377278000,209416191,STK

In [15]:
# to_csv로 Dataframe을 데이터 저장용 파일인 CSV 파일로 바꿀 수 있습니다.
df_krx.to_csv("data/krx.csv", index=False)

In [16]:
# CSV로 저장된 파일을 다시 DataFrame으로 읽어서 확인해 봅니다.
pd.read_csv("data/krx.csv")

,Code,ISU_CD,Name,Market,Dept,Close,ChangeCode,Changes,ChagesRatio,Open,High,Low,Volume,Amount,Marcap,Stocks,MarketId
0,005930,KR7005930003,삼성전자,KOSPI,NaN,79400,1,1100,1.40,79500,79800,78700,4797281,380063908100,474000734470000,5969782550,STK
1,000660,KR7000660001,SK하이닉스,KOSPI,NaN,199800,1,5900,3.04,198700,200500,198100,1422029,283249610300,145454872527000,728002365,STK
2,373220,KR7373220003,LG에너지솔루션,KOSPI,NaN,330000,1,500,0.15,333000,334000,327000,40538,13385655000,77220000000000,234000000,STK
3,207940,KR7207940008,삼성바이오로직스,KOSPI,NaN,916000,2,-14000,-1.51,931000,934000,915000,32421,29916114000,65195384000000,71174000,STK
4,005380,KR7005380001,현대차,KOSPI,NaN,258000,1,3000,1.18,258000,261000,255000,328362,84671381000,54029377278000,209416191,STK
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2823,413300,KR7413300005,티엘엔지니어링,KONEX,일반기업부,1900,1,201,11.83,1900,1900,1900,1,1900,2480478500,1305515,KNX
2824,245450,KR7245450002,씨앤에스링크,KONEX,일반기업부,1398,1,123,9.65,1398,1398,1398,11,15378,2208784080,1579960,KNX
2825,288490,KR7288490006,나라소프트,KONEX,일반기업부,120,1,7,6.19,125,125,120,199,24380,2096589240,17471577,KNX
2826,236030,KR7236030003,씨알푸드,KONEX,일반기업부,555,1,28,5.31,570,580,450,64571,29743280,1128499260,2033332,KNX
2827,308700,KR7308700004,테크엔,KONEX,일반기업부,199,0,0,0.00,0,0,0,0,0,796000000,4000000,KNX

In [17]:
## 도움말 보는 방법
#1 <Shift>+<Tab> : 풍선
#2 함수명? : 도움말
#3 함수명?? : 소스코드까지
pd.read_csv??

Signature:
pd.read_csv(
    filepath_or_buffer: 'FilePath | ReadCsvBuffer[bytes] | ReadCsvBuffer[str]',
    *,
    sep: 'str | None | lib.NoDefault' = <no_default>,
    delimiter: 'str | None | lib.NoDefault' = None,
    header: "int | Sequence[int] | None | Literal['infer']" = 'infer',
    names: 'Sequence[Hashable] | None | lib.NoDefault' = <no_default>,
    index_col: 'IndexLabel | Literal[False] | None' = None,
    usecols: 'UsecolsArgType' = None,
    dtype: 'DtypeArg | None' = None,
    engine: 'CSVEngine | None' = None,
    converters: 'Mapping[Hashable, Callable] | None' = None,
    true_values: 'list | None' = None,
    false_values: 'list | None' = None,
    skipinitialspace: 'bool' = False,
    skiprows: 'list[int] | int | Callable[[Hashable], bool] | None' = None,
    skipfooter: 'int' = 0,
    nrows: 'int | None' = None,
    na_values: 'Hashable | Iterable[Hashable] | Mapping[Hashable, Iterable[Hashable]] | None' = None,
    keep_default_na: 'bool' = True,
    na_filter: 'bool' = True,
    verbose: 'bool | lib.NoDefault' = <no_default>,
    skip_blank_lines: 'bool' = True,
    parse_dates: 'bool | Sequence[Hashable] | None' = None,
    infer_datetime_format: 'bool | lib.NoDefault' = <no_default>,
    keep_date_col: 'bool | lib.NoDefault' = <no_default>,
    date_parser: 'Callable | lib.NoDefault' = <no_default>,
    date_format: 'str | dict[Hashable, str] | None' = None,
    dayfirst: 'bool' = False,
    cache_dates: 'bool' = True,
    iterator: 'bool' = False,
    chunksize: 'int | None' = None,
    compression: 'CompressionOptions' = 'infer',
    thousands: 'str | None' = None,
    decimal: 'str' = '.',
    lineterminator: 'str | None' = None,
    quotechar: 'str' = '"',
    quoting: 'int' = 0,
    doublequote: 'bool' = True,
    escapechar: 'str | None' = None,
    comment: 'str | None' = None,
    encoding: 'str | None' = None,
    encoding_errors: 'str | None' = 'strict',
    dialect: 'str | csv.Dialect | None' = None,
    on_bad_lines: 'str' = 'error',
    delim_whitespace: 'bool | lib.NoDefault' = <no_default>,
    low_memory: 'bool' = True,
    memory_map: 'bool' = False,
    float_precision: "Literal['high', 'legacy'] | None" = None,
    storage_options: 'StorageOptions | None' = None,
    dtype_backend: 'DtypeBackend | lib.NoDefault' = <no_default>,
) -> 'DataFrame | TextFileReader'
Docstring:
Read a comma-separated values (csv) file into DataFrame.

Also supports optionally iterating or breaking of the file
into chunks.

Additional help can be found in the online docs for
`IO Tools <https://pandas.pydata.org/pandas-docs/stable/user_guide/io.html>`_.

Parameters
----------
filepath_or_buffer : str, path object or file-like object
    Any valid string path is acceptable. The string could be a URL. Valid
    URL schemes include http, ftp, s3, gs, and file. For file URLs, a host is
    expected. A local file could be: file://localhost/path/to/table.csv.

    If you want to pass in a path object, pandas accepts any ``os.PathLike``.

    By file-like object, we refer to objects with a ``read()`` method, such as
    a file handle (e.g. via builtin ``open`` function) or ``StringIO``.
sep : str, default ','
    Character or regex pattern to treat as the delimiter. If ``sep=None``, the
    C engine cannot automatically detect
    the separator, but the Python parsing engine can, meaning the latter will
    be used and automatically detect the separator from only the first valid
    row of the file by Python's builtin sniffer tool, ``csv.Sniffer``.
    In addition, separators longer than 1 character and different from
    ``'\s+'`` will be interpreted as regular expressions and will also force
    the use of the Python parsing engine. Note that regex delimiters are prone
    to ignoring quoted data. Regex example: ``'\r\t'``.
delimiter : str, optional
    Alias for ``sep``.
header : int, Sequence of int, 'infer' or None, default 'infer'
    Row number(s) containing column labels and marking the start of the
    data (zero-indexed). Default behavior is to infer the column names: if no ``names``
    are passed the behavior is identical to ``header=0`` and column
    names are inferred from the first line of the file, if column
    names are passed explicitly to ``names`` then the behavior is identical to
    ``header=None``. Explicitly pass ``header=0`` to be able to
    replace existing names. The header can be a list of integers that
    specify row locations for a :class:`~pandas.MultiIndex` on the columns
    e.g. ``[0, 1, 3]``. Intervening rows that are not specified will be
    skipped (e.g. 2 in this example is skipped). Note that this
    parameter ignores commented lines and empty lines if
    ``skip_blank_lines=True``, so ``header=0`` denotes the first line of
    data rather than the first line of the file.
names : Sequence of Hashable, optional
    Sequence of column labels to apply. If the file contains a header row,
    then you should explicitly pass ``header=0`` to override the column names.
    Duplicates in this list are not allowed.
index_col : Hashable, Sequence of Hashable or False, optional
  Column(s) to use as row label(s), denoted either by column labels or column
  indices.  If a sequence of labels or indices is given, :class:`~pandas.MultiIndex`
  will be formed for the row labels.

  Note: ``index_col=False`` can be used to force pandas to *not* use the first
  column as the index, e.g., when you have a malformed file with delimiters at
  the end of each line.
usecols : Sequence of Hashable or Callable, optional
    Subset of columns to select, denoted either by column labels or column indices.
    If list-like, all elements must either
    be positional (i.e. integer indices into the document columns) or strings
    that correspond to column names provided either by the user in ``names`` or
    inferred from the document header row(s). If ``names`` are given, the document
    header row(s) are not taken into account. For example, a valid list-like
    ``usecols`` parameter would be ``[0, 1, 2]`` or ``['foo', 'bar', 'baz']``.
    Element order is ignored, so ``usecols=[0, 1]`` is the same as ``[1, 0]``.
    To instantiate a :class:`~pandas.DataFrame` from ``data`` with element order
    preserved use ``pd.read_csv(data, usecols=['foo', 'bar'])[['foo', 'bar']]``
    for columns in ``['foo', 'bar']`` order or
    ``pd.read_csv(data, usecols=['foo', 'bar'])[['bar', 'foo']]``
    for ``['bar', 'foo']`` order.

    If callable, the callable function will be evaluated against the column
    names, returning names where the callable function evaluates to ``True``. An
    example of a valid callable argument would be ``lambda x: x.upper() in
    ['AAA', 'BBB', 'DDD']``. Using this parameter results in much faster
    parsing time and lower memory usage.
dtype : dtype or dict of {Hashable : dtype}, optional
    Data type(s) to apply to either the whole dataset or individual columns.
    E.g., ``{'a': np.float64, 'b': np.int32, 'c': 'Int64'}``
    Use ``str`` or ``object`` together with suitable ``na_values`` settings
    to preserve and not interpret ``dtype``.
    If ``converters`` are specified, they will be applied INSTEAD
    of ``dtype`` conversion.

    .. versionadded:: 1.5.0

        Support for ``defaultdict`` was added. Specify a ``defaultdict`` as input where
        the default determines the ``dtype`` of the columns which are not explicitly
        listed.
engine : {'c', 'python', 'pyarrow'}, optional
    Parser engine to use. The C and pyarrow engines are faster, while the python engine
    is currently more feature-complete. Multithreading is currently only supported by
    the pyarrow engine.

    .. versionadded:: 1.4.0

        The 'pyarrow' engine was added as an *experimental* engine, and some features
        are unsupported, or may not work correctly, with this engine.
converters : dict of {Hashable : Callable}, optional
    Functions for converting values in specified columns. Keys can either
    be column labels or column indices.
true_values : list, optional
    Values to consider as ``True`` in addition to case-insensitive variants of 'True'.
false_values : list, optional
    Values to consider as ``False`` in addition to case-insensitive variants of 'False'.
skipinitialspace : bool, default False
    Skip spaces after delimiter.
skiprows : int, list of int or Callable, optional
    Line numbers to skip (0-indexed) or number of lines to skip (``int``)
    at the start of the file.

    If callable, the callable function will be evaluated against the row
    indices, returning ``True`` if the row should be skipped and ``False`` otherwise.
    An example of a valid callable argument would be ``lambda x: x in [0, 2]``.
skipfooter : int, default 0
    Number of lines at bottom of file to skip (Unsupported with ``engine='c'``).
nrows : int, optional
    Number of rows of file to read. Useful for reading pieces of large files.
na_values : Hashable, Iterable of Hashable or dict of {Hashable : Iterable}, optional
    Additional strings to recognize as ``NA``/``NaN``. If ``dict`` passed, specific
    per-column ``NA`` values.  By default the following values are interpreted as
    ``NaN``: " ", "#N/A", "#N/A N/A", "#NA", "-1.#IND", "-1.#QNAN", "-NaN", "-nan",
    "1.#IND", "1.#QNAN", "<NA>", "N/A", "NA", "NULL", "NaN", "None",
    "n/a", "nan", "null ".

keep_default_na : bool, default True
    Whether or not to include the default ``NaN`` values when parsing the data.
    Depending on whether ``na_values`` is passed in, the behavior is as follows:

    * If ``keep_default_na`` is ``True``, and ``na_values`` are specified, ``na_values``
      is appended to the default ``NaN`` values used for parsing.
    * If ``keep_default_na`` is ``True``, and ``na_values`` are not specified, only
      the default ``NaN`` values are used for parsing.
    * If ``keep_default_na`` is ``False``, and ``na_values`` are specified, only
      the ``NaN`` values specified ``na_values`` are used for parsing.
    * If ``keep_default_na`` is ``False``, and ``na_values`` are not specified, no
      strings will be parsed as ``NaN``.

    Note that if ``na_filter`` is passed in as ``False``, the ``keep_default_na`` and
    ``na_values`` parameters will be ignored.
na_filter : bool, default True
    Detect missing value markers (empty strings and the value of ``na_values``). In
    data without any ``NA`` values, passing ``na_filter=False`` can improve the
    performance of reading a large file.
verbose : bool, default False
    Indicate number of ``NA`` values placed in non-numeric columns.

    .. deprecated:: 2.2.0
skip_blank_lines : bool, default True
    If ``True``, skip over blank lines rather than interpreting as ``NaN`` values.
parse_dates : bool, list of Hashable, list of lists or dict of {Hashable : list}, default False
    The behavior is as follows:

    * ``bool``. If ``True`` -> try parsing the index. Note: Automatically set to
      ``True`` if ``date_format`` or ``date_parser`` arguments have been passed.
    * ``list`` of ``int`` or names. e.g. If ``[1, 2, 3]`` -> try parsing columns 1, 2, 3
      each as a separate date column.
    * ``list`` of ``list``. e.g.  If ``[[1, 3]]`` -> combine columns 1 and 3 and parse
      as a single date column. Values are joined with a space before parsing.
    * ``dict``, e.g. ``{'foo' : [1, 3]}`` -> parse columns 1, 3 as date and call
      result 'foo'. Values are joined with a space before parsing.

    If a column or index cannot be represented as an array of ``datetime``,
    say because of an unparsable value or a mixture of timezones, the column
    or index will be returned unaltered as an ``object`` data type. For
    non-standard ``datetime`` parsing, use :func:`~pandas.to_datetime` after
    :func:`~pandas.read_csv`.

    Note: A fast-path exists for iso8601-formatted dates.
infer_datetime_format : bool, default False
    If ``True`` and ``parse_dates`` is enabled, pandas will attempt to infer the
    format of the ``datetime`` strings in the columns, and if it can be inferred,
    switch to a faster method of parsing them. In some cases this can increase
    the parsing speed by 5-10x.

    .. deprecated:: 2.0.0
        A strict version of this argument is now the default, passing it has no effect.

keep_date_col : bool, default False
    If ``True`` and ``parse_dates`` specifies combining multiple columns then
    keep the original columns.
date_parser : Callable, optional
    Function to use for converting a sequence of string columns to an array of
    ``datetime`` instances. The default uses ``dateutil.parser.parser`` to do the
    conversion. pandas will try to call ``date_parser`` in three different ways,
    advancing to the next if an exception occurs: 1) Pass one or more arrays
    (as defined by ``parse_dates``) as arguments; 2) concatenate (row-wise) the
    string values from the columns defined by ``parse_dates`` into a single array
    and pass that; and 3) call ``date_parser`` once for each row using one or
    more strings (corresponding to the columns defined by ``parse_dates``) as
    arguments.

    .. deprecated:: 2.0.0
       Use ``date_format`` instead, or read in as ``object`` and then apply
       :func:`~pandas.to_datetime` as-needed.
date_format : str or dict of column -> format, optional
    Format to use for parsing dates when used in conjunction with ``parse_dates``.
    The strftime to parse time, e.g. :const:`"%d/%m/%Y"`. See
    `strftime documentation
    <https://docs.python.org/3/library/datetime.html
    #strftime-and-strptime-behavior>`_ for more information on choices, though
    note that :const:`"%f"` will parse all the way up to nanoseconds.
    You can also pass:

    - "ISO8601", to parse any `ISO8601 <https://en.wikipedia.org/wiki/ISO_8601>`_
        time string (not necessarily in exactly the same format);
    - "mixed", to infer the format for each element individually. This is risky,
        and you should probably use it along with `dayfirst`.

    .. versionadded:: 2.0.0
dayfirst : bool, default False
    DD/MM format dates, international and European format.
cache_dates : bool, default True
    If ``True``, use a cache of unique, converted dates to apply the ``datetime``
    conversion. May produce significant speed-up when parsing duplicate
    date strings, especially ones with timezone offsets.

iterator : bool, default False
    Return ``TextFileReader`` object for iteration or getting chunks with
    ``get_chunk()``.
chunksize : int, optional
    Number of lines to read from the file per chunk. Passing a value will cause the
    function to return a ``TextFileReader`` object for iteration.
    See the `IO Tools docs
    <https://pandas.pydata.org/pandas-docs/stable/io.html#io-chunking>`_
    for more information on ``iterator`` and ``chunksize``.

compression : str or dict, default 'infer'
    For on-the-fly decompression of on-disk data. If 'infer' and 'filepath_or_buffer' is
    path-like, then detect compression from the following extensions: '.gz',
    '.bz2', '.zip', '.xz', '.zst', '.tar', '.tar.gz', '.tar.xz' or '.tar.bz2'
    (otherwise no compression).
    If using 'zip' or 'tar', the ZIP file must contain only one data file to be read in.
    Set to ``None`` for no decompression.
    Can also be a dict with key ``'method'`` set
    to one of {``'zip'``, ``'gzip'``, ``'bz2'``, ``'zstd'``, ``'xz'``, ``'tar'``} and
    other key-value pairs are forwarded to
    ``zipfile.ZipFile``, ``gzip.GzipFile``,
    ``bz2.BZ2File``, ``zstandard.ZstdDecompressor``, ``lzma.LZMAFile`` or
    ``tarfile.TarFile``, respectively.
    As an example, the following could be passed for Zstandard decompression using a
    custom compression dictionary:
    ``compression={'method': 'zstd', 'dict_data': my_compression_dict}``.

    .. versionadded:: 1.5.0
        Added support for `.tar` files.

    .. versionchanged:: 1.4.0 Zstandard support.

thousands : str (length 1), optional
    Character acting as the thousands separator in numerical values.
decimal : str (length 1), default '.'
    Character to recognize as decimal point (e.g., use ',' for European data).
lineterminator : str (length 1), optional
    Character used to denote a line break. Only valid with C parser.
quotechar : str (length 1), optional
    Character used to denote the start and end of a quoted item. Quoted
    items can include the ``delimiter`` and it will be ignored.
quoting : {0 or csv.QUOTE_MINIMAL, 1 or csv.QUOTE_ALL, 2 or csv.QUOTE_NONNUMERIC, 3 or csv.QUOTE_NONE}, default csv.QUOTE_MINIMAL
    Control field quoting behavior per ``csv.QUOTE_*`` constants. Default is
    ``csv.QUOTE_MINIMAL`` (i.e., 0) which implies that only fields containing special
    characters are quoted (e.g., characters defined in ``quotechar``, ``delimiter``,
    or ``lineterminator``.
doublequote : bool, default True
   When ``quotechar`` is specified and ``quoting`` is not ``QUOTE_NONE``, indicate
   whether or not to interpret two consecutive ``quotechar`` elements INSIDE a
   field as a single ``quotechar`` element.
escapechar : str (length 1), optional
    Character used to escape other characters.
comment : str (length 1), optional
    Character indicating that the remainder of line should not be parsed.
    If found at the beginning
    of a line, the line will be ignored altogether. This parameter must be a
    single character. Like empty lines (as long as ``skip_blank_lines=True``),
    fully commented lines are ignored by the parameter ``header`` but not by
    ``skiprows``. For example, if ``comment='#'``, parsing
    ``#empty\na,b,c\n1,2,3`` with ``header=0`` will result in ``'a,b,c'`` being
    treated as the header.
encoding : str, optional, default 'utf-8'
    Encoding to use for UTF when reading/writing (ex. ``'utf-8'``). `List of Python
    standard encodings
    <https://docs.python.org/3/library/codecs.html#standard-encodings>`_ .

encoding_errors : str, optional, default 'strict'
    How encoding errors are treated. `List of possible values
    <https://docs.python.org/3/library/codecs.html#error-handlers>`_ .

    .. versionadded:: 1.3.0

dialect : str or csv.Dialect, optional
    If provided, this parameter will override values (default or not) for the
    following parameters: ``delimiter``, ``doublequote``, ``escapechar``,
    ``skipinitialspace``, ``quotechar``, and ``quoting``. If it is necessary to
    override values, a ``ParserWarning`` will be issued. See ``csv.Dialect``
    documentation for more details.
on_bad_lines : {'error', 'warn', 'skip'} or Callable, default 'error'
    Specifies what to do upon encountering a bad line (a line with too many fields).
    Allowed values are :

    - ``'error'``, raise an Exception when a bad line is encountered.
    - ``'warn'``, raise a warning when a bad line is encountered and skip that line.
    - ``'skip'``, skip bad lines without raising or warning when they are encountered.

    .. versionadded:: 1.3.0

    .. versionadded:: 1.4.0

        - Callable, function with signature
          ``(bad_line: list[str]) -> list[str] | None`` that will process a single
          bad line. ``bad_line`` is a list of strings split by the ``sep``.
          If the function returns ``None``, the bad line will be ignored.
          If the function returns a new ``list`` of strings with more elements than
          expected, a ``ParserWarning`` will be emitted while dropping extra elements.
          Only supported when ``engine='python'``

    .. versionchanged:: 2.2.0

        - Callable, function with signature
          as described in `pyarrow documentation
          <https://arrow.apache.org/docs/python/generated/pyarrow.csv.ParseOptions.html
          #pyarrow.csv.ParseOptions.invalid_row_handler>`_ when ``engine='pyarrow'``

delim_whitespace : bool, default False
    Specifies whether or not whitespace (e.g. ``' '`` or ``'\t'``) will be

#### (실습) SP500 종목 리스팅 데이터를 읽고, CSV 파일로 저장하고, CSV 파일 읽어서 확인

In [18]:
import pandas as pd
import FinanceDataReader as fdr

In [19]:
df_sp500 = fdr.StockListing("SP500")
df_sp500

,Symbol,Name,Sector,Industry
0,MMM,3M,Industrials,Industrial Conglomerates
1,AOS,A. O. Smith,Industrials,Building Products
2,ABT,Abbott Laboratories,Health Care,Health Care Equipment
3,ABBV,AbbVie,Health Care,Biotechnology
4,ACN,Accenture,Information Technology,IT Consulting & Other Services
...,...,...,...,...
498,XYL,Xylem Inc.,Industrials,Industrial Machinery & Supplies & Components
499,YUM,Yum! Brands,Consumer Discretionary,Restaurants
500,ZBRA,Zebra Technologies,Information Technology,Electronic Equipment & Instruments
501,ZBH,Zimmer Biomet,Health Care,Health Care Equipment
502,ZTS,Zoetis,Health Care,Pharmaceuticals

In [20]:
df_sp500.to_csv("data/sp500.csv", index=False)

In [21]:
pd.read_csv("data/sp500.csv")

,Symbol,Name,Sector,Industry
0,MMM,3M,Industrials,Industrial Conglomerates
1,AOS,A. O. Smith,Industrials,Building Products
2,ABT,Abbott Laboratories,Health Care,Health Care Equipment
3,ABBV,AbbVie,Health Care,Biotechnology
4,ACN,Accenture,Information Technology,IT Consulting & Other Services
...,...,...,...,...
498,XYL,Xylem Inc.,Industrials,Industrial Machinery & Supplies & Components
499,YUM,Yum! Brands,Consumer Discretionary,Restaurants
500,ZBRA,Zebra Technologies,Information Technology,Electronic Equipment & Instruments
501,ZBH,Zimmer Biomet,Health Care,Health Care Equipment
502,ZTS,Zoetis,Health Care,Pharmaceuticals